# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Apple API
  description: Apple api
  version: "1.0.0"
schemes:
  - http
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /apples:
    get:
      summary: Apples
      description: Returns apples
      tags:
        - Apple
      responses:
        200:
          description: An array of apples
          schema:
            type: array
            items:
              $ref: '#/definitions/Apple'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Apples
      description: Returns apples
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Apple"
      tags:
        - Apple
      responses:
        200:
          description: An apple
          schema:
            $ref: '#/definitions/Apple'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Apple:
    type: object
    properties:
      size:
        type: number
        format: double
        description: size of an apple
      color:
        type: string
        description: color of an apple
